### PR TITLE
WIP - fix sct docker for sct beta version 5

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes address issue explained [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2005#issuecomment-514296138)

The current fix for git is applied only for ubuntu 18.04. TODO: address the other distrib.

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
thanks for the fix @alexfoias but shouldn't you duplicate those changes for other distros?

**Comment by alexfoias** [comment]
I tested the [current version] (https://github.com/neuropoly/sct_docker/commit/f4e659164662b7466ffae66960cf085d566396eb)

And here is the status: 
```
Successfully tagged sct-4.0.0-beta.5-fedora-28:latest
ERROR:root:sct-4.0.0-beta.5-centos-7 failed with error code 1
Done building images
ERROR:root:sct-4.0.0-beta.5-ubuntu-14.04 failed with error code 1
ERROR:root:sct-4.0.0-beta.5-ubuntu-16.04 failed with error code 1
INFO:root:sct-4.0.0-beta.5-ubuntu-18.04 finished successfully
INFO:root:sct-4.0.0-beta.5-official finished successfully
ERROR:root:sct-4.0.0-beta.5-debian-8 failed with error code 1
INFO:root:sct-4.0.0-beta.5-debian-9 finished successfully
ERROR:root:sct-4.0.0-beta.5-fedora-25 failed with error code 1
INFO:root:sct-4.0.0-beta.5-fedora-26 finished successfully
INFO:root:sct-4.0.0-beta.5-fedora-27 finished successfully
INFO:root:sct-4.0.0-beta.5-fedora-28 finished successfully
ERROR:root:sct-4.0.0-beta.5-centos-7 failed with error code 1
[1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1]
ERROR:root:Not proceeding further as one distro failed
```

**Comment by jcohenadad** [comment]
> I tested the [current version] ([f4e6591](https://github.com/neuropoly/sct_docker/commit/f4e659164662b7466ffae66960cf085d566396eb))
> 
> And here is the status:
> 
> ```
> Successfully tagged sct-4.0.0-beta.5-fedora-28:latest
> ERROR:root:sct-4.0.0-beta.5-centos-7 failed with error code 1
> Done building images
> ERROR:root:sct-4.0.0-beta.5-ubuntu-14.04 failed with error code 1
> ERROR:root:sct-4.0.0-beta.5-ubuntu-16.04 failed with error code 1
> INFO:root:sct-4.0.0-beta.5-ubuntu-18.04 finished successfully
> INFO:root:sct-4.0.0-beta.5-official finished successfully
> ERROR:root:sct-4.0.0-beta.5-debian-8 failed with error code 1
> INFO:root:sct-4.0.0-beta.5-debian-9 finished successfully
> ERROR:root:sct-4.0.0-beta.5-fedora-25 failed with error code 1
> INFO:root:sct-4.0.0-beta.5-fedora-26 finished successfully
> INFO:root:sct-4.0.0-beta.5-fedora-27 finished successfully
> INFO:root:sct-4.0.0-beta.5-fedora-28 finished successfully
> ERROR:root:sct-4.0.0-beta.5-centos-7 failed with error code 1
> [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1]
> ERROR:root:Not proceeding further as one distro failed
> ```

do you need help to fix those errors or can you do it?

**Comment by alexfoias** [comment]
The problem seems to be the version of python in the container for centos 7, ubuntu 14.04, fedora 25. 

```
  Downloading https://files.pythonhosted.org/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz (23.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-V2Ghvd/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
```

For ubuntu 16.04 the message is different:

```
Collecting matplotlib>=1.5.1 (from fsleyes)
  Downloading https://files.pythonhosted.org/packages/12/d1/7b12cd79c791348cb0c78ce6e7d16bd72992f13c9f1e8e43d2725a6d8adf/matplotlib-3.1.1.tar.gz (37.8MB)
    Complete output from command python setup.py egg_info:
    
    Beginning with Matplotlib 3.1, Python 3.6 or above is required.
    
    This may be due to an out of date pip.
    
    Make sure you have pip >= 9.0.1.

```

For debian 8 is a scipy issue as well:

```
Step 34/43 : RUN bash -i -c "pip install --user --upgrade scipy"
 ---> Running in 221449fa76aa
bash: cannot set terminal process group (1): Inappropriate ioctl for device
bash: no job control in this shell
Downloading/unpacking scipy
  Running setup.py (path:/tmp/pip-build-eQCYYa/scipy/setup.py) egg_info for package scipy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-eQCYYa/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-eQCYYa/scipy/setup.py", line 31, in <module>

    raise RuntimeError("Python version >= 3.5 required.")

RuntimeError: Python version >= 3.5 required.

```

**Comment by jcohenadad** [comment]
@gmotzespina could you please chip in? Or @zougloub if you have some time

**Comment by zougloub** [comment]
Taking a quick look...

**Comment by zougloub** [comment]
Refactored a bunch of stuff in master.
There are workarounds for https://github.com/neuropoly/spinalcordtoolbox/issues/2362 and others (will open issues).

**Pull request closed without merging**
